platform: linux

image_resource:
  type: registry-image
  source:
    repository: rust
    tag: alpine

inputs: 
  - name: repository
    path: .

outputs: 
  - name: release
    path: target/release

caches: 
  - path: target

params: 
  CARGO_COMMAND: ""

run:
  path: /bin/sh
  args:
    - -ce
    - exec cargo $CARGO_COMMAND
