---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY: cirocosta/node_extra_exporter
  TAG: latest
  CONTEXT: repository
  TARGET: test

inputs:
- name: repository

run: {path: build}
