resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/node_extra_exporter

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/node_extra_exporter
      username: ((docker-user))
      password: ((docker-password))

  - name: builder
    type: registry-image
    source:
      repository: cirocosta/builder

jobs:
  - name: build
    public: true
    serial: true
    plan:
      - aggregate:
        - get: repository
          trigger: true
        - get: builder
      - aggregate:
        - task: build
          image: builder
          privileged: true
          file: repository/ci/tasks/build-image.yml
        - task: test
          params: { TARGET: test }
          image: builder
          privileged: true
          file: repository/ci/tasks/build-image.yml
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params: {image: image/image.tar}
