resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/node_extra_exporter

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/node_extra_exporter
      username: ((docker-user))
      password: ((docker-password))

  - name: builder
    type: registry-image
    source:
      repository: cirocosta/builder

jobs:
  - name: build
    public: true
    plan:
      - get: repository
        trigger: true
      - aggregate:
        - do:
          - get: builder
            trigger: true
          - aggregate:
            - task: build
              image: builder
              privileged: true
              file: repository/ci/tasks/build-image.yml
            - task: test
              image: builder
              privileged: true
              file: repository/ci/tasks/test-image.yml
        - do:
          - task: test-arm
            tags: [arm]
            params: {CARGO_COMMAND: "test"}
            file: repository/ci/tasks/arm-run.yml
          - task: build-arm
            tags: [arm]
            params: {CARGO_COMMAND: "build --release"}
            file: repository/ci/tasks/arm-run.yml
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params: {image: image/image.tar}
